import './test_background.js';
import './test_clock.js';
import './test_demo.js';
import './test_location_backend.js';
import './test_location.js';
import './test_refresh.js';
import './test_util.js';
import './test_varsnap.js';
import './test_weather.js';
