kind: pipeline
type: docker
name: test

steps:
  - name: Test Node
    image: satantime/puppeteer-node:24-bookworm-slim
    commands:
      - ln -fs .env.development .env
      - apt-get update && apt-get install -y curl git xz-utils
      - curl https://qlty.sh | sh
      - npm ci
      - npm run test-node
      - ~/.qlty/bin/qlty coverage publish .coverage/clover.xml --override-commit-sha "$DRONE_COMMIT_SHA" --override-branch "$DRONE_BRANCH" --override-build-id "$DRONE_BUILD_NUMBER"
    environment:
      QLTY_COVERAGE_TOKEN: qltcp_9wA53zyfwdF3cRxZ

  - name: Test Bash
    image: koalaman/shellcheck-alpine:stable
    commands:
      - ln -fs .env.development .env
      - shellcheck -x bin/*.sh

  - name: Test Dockerfile
    image: hadolint/hadolint:latest-alpine
    commands:
      - hadolint Dockerfile --ignore=DL3008 --ignore=SC2046 --ignore=SC2006

  - name: Test Nginx
    image: getpagespeed/gixy:v0.2.7
    commands:
      - gixy config/nginx/*

  - name: Build Docker Container
    depends_on:
      - Test Node
      - Test Bash
      - Test Dockerfile
      - Test Nginx
    image: plugins/docker
    settings:
      repo: codemancer
      tags: test
      dry_run: true

  - name: Deploy
    depends_on:
      - Build Docker Container
    environment:
      SSH_KEY:
        from_secret: ssh_key
    image: albertyw/ssh-client:4.1.10
    commands:
      - ssh-keyscan direct.albertyw.com >> /root/.ssh/known_hosts
      - echo "$${SSH_KEY}" > /root/.ssh/id_ed25519
      - chmod 600 /root/.ssh/id_ed25519
      - ssh albertyw@direct.albertyw.com codemancer/bin/deploy.sh master
    when:
      branch:
        - master

  - name: Purge Cache
    depends_on:
      - Deploy
    image: curlimages/curl:8.15.0
    commands:
      - |-
        curl -X DELETE "https://api.cloudflare.com/client/v4/zones/$${CLOUDFLARE_ZONE_ID}/purge_cache" -H "Authorization: Bearer $${CLOUDFLARE_API_KEY}" -H "Content-Type: application/json" --data '{"purge_everything":true}'
    when:
      branch:
        - master
    environment:
      CLOUDFLARE_ZONE_ID:
        from_secret: CLOUDFLARE_ZONE_ID
      CLOUDFLARE_API_KEY:
        from_secret: CLOUDFLARE_API_KEY
