kind: pipeline
type: docker
name: test

volumes:
  - name: ssh_key
    host:
      path: /home/albertyw/.ssh/id_ed25519

steps:
  - name: Test Node
    image: node:14
    commands:
      - ln -fs .env.development .env
      - npm install
      - npm test

  - name: Test Bash
    image: koalaman/shellcheck-alpine:stable
    commands:
      - ln -fs .env.development .env
      - shellcheck -x bin/*.sh

  - name: Test Dockerfile
    image: hadolint/hadolint:latest-alpine
    commands:
      - hadolint Dockerfile --ignore=DL3008 --ignore=SC2046 --ignore=SC2006

  - name: Build Docker Container
    depends_on:
      - Test Node
      - Test Bash
      - Test Dockerfile
    image: plugins/docker
    settings:
      repo: codemancer
      tags: test
      dry_run: true

  - name: Deploy
    depends_on:
      - Build Docker Container
    image: appleboy/drone-ssh
    settings:
      host: direct.albertyw.com
      username: albertyw
      key_path: /root/ssh/id_ed25519
      script:
        - "/home/albertyw/codemancer/bin/deploy.sh"
    volumes:
      - name: ssh_key
        path: /root/ssh/id_ed25519
    when:
      branch:
        - master
