kind: pipeline
type: docker
name: test

volumes:
  - name: ssh_key
    host:
      path: /home/albertyw/.ssh/id_ed25519

steps:
  - name: Test Node
    image: node:16
    commands:
      - apt-get update && apt-get install -y fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libcups2 libgbm1 libgtk-3-0 libnspr4 libnss3 libx11-xcb1 libxss1 libxtst6 lsb-release xdg-utils
      - ln -fs .env.development .env
      - npm ci
      - npm run google
      - npm run test-node

  - name: Test Bash
    image: koalaman/shellcheck-alpine:stable
    commands:
      - ln -fs .env.development .env
      - shellcheck -x bin/*.sh

  - name: Test Dockerfile
    image: hadolint/hadolint:latest-alpine
    commands:
      - hadolint Dockerfile --ignore=DL3008 --ignore=SC2046 --ignore=SC2006

  - name: Test Nginx
    image: yandex/gixy:0.1.20
    commands:
      - gixy config/nginx/*

  - name: Build Docker Container
    depends_on:
      - Test Node
      - Test Bash
      - Test Dockerfile
      - Test Nginx
    image: plugins/docker
    settings:
      repo: codemancer
      tags: test
      dry_run: true

  - name: Deploy
    depends_on:
      - Build Docker Container
    image: appleboy/drone-ssh
    settings:
      host: direct.albertyw.com
      username: albertyw
      key_path: /root/ssh/id_ed25519
      script:
        - "/home/albertyw/codemancer/bin/deploy.sh master"
    volumes:
      - name: ssh_key
        path: /root/ssh/id_ed25519
    when:
      branch:
        - master

  - name: Purge Cache
    depends_on:
      - Deploy
    image: curlimages/curl:7.75.0
    commands:
      - |-
        curl -X DELETE "https://api.cloudflare.com/client/v4/zones/$${CLOUDFLARE_ZONE_ID}/purge_cache" -H "Authorization: Bearer $${CLOUDFLARE_API_KEY}" -H "Content-Type: application/json" --data '{"purge_everything":true}'
    when:
      branch:
        - master
    environment:
      CLOUDFLARE_ZONE_ID:
        from_secret: CLOUDFLARE_ZONE_ID
      CLOUDFLARE_API_KEY:
        from_secret: CLOUDFLARE_API_KEY
